###Registration
POST {{baseUrl}}/auth/sign-up
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="dto"
Content-Type: application/json

{
  "email": "example@mail.com",
  "password": "Example8!",
  "fullName": "Abraham Lincoln",
  "currencyCode": "USD"
}


###Token verification
GET {{baseUrl}}/auth/verify?token=eyJhbGciOiJIUzM4NCJ9.eyJwdXJwb3NlIjoiZW1haWxfdmVyaWZpY2F0aW9uIiwic3ViIjoiZXhhbXBsZUBtYWlsLmNvbSIsImlhdCI6MTc3OTcwNDk3MiwiZXhwIjoxNzc5NzA1ODcyfQ.plqKd_YorAtVIQgGMhcEoBPaR6m9Hna6JTvmeqSHJH4syF3e49-HifwsyOtxrzUj


###Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "maria@example.com",
  "password": "Example8!"
}

> {% client.global.set("accessToken", response.body.accessToken) %}

###Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}


###Profile
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

###Create category
POST {{baseUrl}}/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Salary",
  "type": "INCOME",
  "icon": "coins"
}

###Mail verifying

GET {{baseUrl}}/users/verify-email?token=
Accept-Language: en



###Delete category
DELETE {{baseUrl}}/categories/9?10
Authorization: Bearer {{accessToken}}

###Delete user
DELETE {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

###Get first transaction page without cursor
GET {{baseUrl}}/transactions?limit=10
Authorization: Bearer {{accessToken}}

###Get first transaction page with date-filter
GET http://localhost:8080/api/v1/transactions?limit=5&dateFrom=2025-05-20&dateTo=2025-05-27
Authorization: Bearer {{accessToken}}

###Get second transaction page with cursor from response
GET http://localhost:8080/api/v1/transactions?limit=5&cursor=MjAyNS0wNS0yN3wxMjM0NQ==
Authorization: Bearer {{accessToken}}


###Get first transaction page with folter by account and category
GET http://localhost:8080/api/v1/transactions?limit=10&accountId=3&categoryId=5&type=EXPENSE
Authorization: Bearer {{accessToken}}





