###Registration
POST {{baseUrl}}/auth/sign-up
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="dto"
Content-Type: application/json

{
  "email": "example@mail.com",
  "password": "Example8!",
  "fullName": "Abraham Lincoln",
  "currencyCode": "USD"
}


###Token verification
GET {{baseUrl}}/auth/verify?token=eyJhbGciOiJIUzM4NCJ9.eyJwdXJwb3NlIjoiZW1haWxfdmVyaWZpY2F0aW9uIiwic3ViIjoiZXhhbXBsZUBtYWlsLmNvbSIsImlhdCI6MTc3OTMxNzY2MywiZXhwIjoxNzc5MzE4NTYzfQ.VOmzmSwqmwImeu0W3GIdDcAPQKKiqtLd_Y9chkraV5uCq7QorEGt0Ftvxg5KiA7d


###Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "example@mail.com",
  "password": "Example8!"
}

> {% client.global.set("accessToken", response.body.accessToken) %}

###Profile
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

###Create category
POST {{baseUrl}}/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Salary",
  "type": "INCOME",
  "icon": "coins"
}

###Mail verifying

GET {{baseUrl}}/users/verify-email?token=
Accept-Language: en



###Delete category
DELETE {{baseUrl}}/categories/9?10
Authorization: Bearer {{accessToken}}




