###Registration
POST {{baseUrl}}/auth/sign-up
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="dto"
Content-Type: application/json

{
  "email": "example@mail.com",
  "password": "Example8!",
  "fullName": "Abraham Lincoln",
  "currencyCode": "USD"
}


###Token verification
GET {{baseUrl}}/auth/verify?token=eyJhbGciOiJIUzM4NCJ9.eyJwdXJwb3NlIjoiZW1haWxfdmVyaWZpY2F0aW9uIiwic3ViIjoiZXhhbXBsZUBtYWlsLmNvbSIsImlhdCI6MTc3OTcwNDk3MiwiZXhwIjoxNzc5NzA1ODcyfQ.plqKd_YorAtVIQgGMhcEoBPaR6m9Hna6JTvmeqSHJH4syF3e49-HifwsyOtxrzUj


###Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "maria@example.com",
  "password": "Example8!"
}

> {% client.global.set("accessToken", response.body.accessToken) %}

###Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}


###Profile
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

###Create category
POST {{baseUrl}}/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Salarу5y",
  "type": "INCOME",
  "icon": "WALLET"
}

###Update category
PATCH {{baseUrl}}/categories/7
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Salary",
  "icon": "DATABASE"
}


###Get categories
GET {{baseUrl}}/categories
Authorization: Bearer {{accessToken}}


###Mail verifying

GET {{baseUrl}}/users/verify-email?token=
Accept-Language: en



###Delete category
DELETE {{baseUrl}}/categories/9?10
Authorization: Bearer {{accessToken}}

###Delete user
DELETE {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}

###Get first transaction page without cursor
GET {{baseUrl}}/transactions?limit=10
Authorization: Bearer {{accessToken}}

###Get first transaction page with date-filter
GET{{baseUrl}}/transactions?limit=5&dateFrom=2025-05-20&dateTo=2025-05-27
Authorization: Bearer {{accessToken}}

###Get second transaction page with cursor from response
GET {{baseUrl}}/transactions?limit=5&cursor=MjAyNS0wNS0yN3wxMjM0NQ==
Authorization: Bearer {{accessToken}}


###Get first transaction page with folter by account and category
GET {{baseUrl}}/transactions?limit=10&accountId=3&categoryId=5&type=EXPENSE
Authorization: Bearer {{accessToken}}

###Update transaction
PATCH{{baseUrl}}/transactions/22
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "amount": "135.80",
  "description": "всяка фігня",
  "categoryId": "5",
  "date": "2026-01-01"
}

###Create transaction
POST{{baseUrl}}/transactions
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept-Language: en

--WebAppBoundary
Content-Disposition: form-data; name="dto"
Content-Type: application/json

{
  "amount": 100.555,
  "type": "INCOME",
  "categoryId": 8,
  "date": "2026-05-09",
  "description": null,
  "accountId": 2
}





